"""empty message

Revision ID: 6824bf7088b7
Revises: 
Create Date: 2021-09-03 13:18:59.542428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6824bf7088b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'content',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    op.alter_column('images', 'commodity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'commodity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('images', 'content',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
